Lint/UnderscorePrefixedVariableName:
  Exclude:
    - 'spec/mixlib/shellout/windows_spec.rb'

# Configuration parameters: ContextCreatingMethods.
Lint/UselessAccessModifier:
  Exclude:
    - 'lib/mixlib/shellout/windows/core_ext.rb'
Security/Eval:
  Enabled: false
Layout/EndOfLine:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
Lint/ParenthesesAsGroupedExpression:
  Enabled: false
Lint/ShadowedException:
  Enabled: false
