name: All checks pass
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  allchecks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: read
    steps:
      - uses: wechuli/allcheckspassed@e22f45a4f25f4cf821d1273705ac233355400db1 # v1.2.0
        with:
          # This seems to be working lately even for external
          # contributors, so maybe we don't need to exclude it?
          checks_exclude: "SonarCloud Code Analysis"
          # Retry every minute for 30 minutes...
          retries: 30
